/**
 *
 * (c) Copyright Ascensio System SIA 2021
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

(function(b,p){function r(a){b.Asc.plugin.ie_channel?b.Asc.plugin.ie_channel.postMessage(a):b.parent.postMessage(a,"*")}function n(a,d){if(!a||"object"!=typeof a&&"array"!=typeof a)return a;d=d===p?{}:d;for(var f in a)a.hasOwnProperty(f)&&(d[f]=a[f]&&"object"===typeof a[f]?n(a[f]):a[f]);return d}function m(a){var d=b.location.search,f=a+"=";a=d.indexOf(f);return 0<=a?(a+=f.length,f=d.indexOf("&",a),0>f&&(f=d.length),d.substring(a,f)):p}function k(){var a=m("windowID");a&&(b.Asc.plugin.windowID=a,
b.Asc.plugin.guid||(b.Asc.plugin.guid=decodeURIComponent(m("guid"))));return p!==a?!0:!1}function l(a){if(b.Asc&&b.Asc.plugin)if(b.plugin_onMessage)b.Asc.supportOrigins[a.origin]&&b.plugin_onMessage(a);else if(b.Asc.plugin._initInternal&&"string"==typeof a.data){var d={};try{d=JSON.parse(a.data)}catch(f){d={}}"plugin_init"==d.type&&(b.Asc.supportOrigins[a.origin]=!0,b.Asc.plugin.ie_channel_check(a),eval(d.data))}}b.Asc=b.Asc||{};b.Asc.plugin={};b.Asc.plugin.ie_channel=null;b.Asc.plugin.ie_channel_check=
function(a){var d=navigator.userAgent.toLowerCase();(-1<d.indexOf("msie")||-1<d.indexOf("trident"))&&a.ports&&a.ports[0]&&(this.ie_channel=a.ports[0])};b.Asc.plugin.tr_init=!1;b.Asc.plugin.tr=function(a){return a};b.Asc.scope={};b.Asc.scope.prototype={clear:function(){for(var a in b.Asc.scope)delete b.Asc.scope[a]}};b.onload=function(){if(b.Asc&&b.Asc.plugin){var a=new XMLHttpRequest;a.open("get","./config.json",!0);a.responseType="json";a.onload=function(){if(b.Asc&&b.Asc.plugin){if(404===a.status)return a.onerror();
if(200==a.status||0==a.status&&4==a.readyState){var d=a.response;"string"==typeof d&&(d=JSON.parse(d));n(d,b.Asc.plugin);d={type:"initialize",guid:b.Asc.plugin.guid};k()&&(d.windowID=b.Asc.plugin.windowID);var f=document.body;f&&!0!==b.Asc.plugin.enableDrops&&(f.ondrop=function(c){c&&c.preventDefault&&c.preventDefault();return!1},f.ondragenter=function(c){c&&c.preventDefault&&c.preventDefault();return!1},f.ondragover=function(c){c&&c.preventDefault&&c.preventDefault();c&&c.dataTransfer&&(c.dataTransfer.dropEffect=
"none");return!1});b.Asc.plugin._initInternal=!0;b.parent.postMessage(JSON.stringify(d),"*")}}};a.onerror=function(){if(b.Asc&&b.Asc.plugin&&k()){var d={type:"initialize",guid:b.Asc.plugin.guid};d.windowID=b.Asc.plugin.windowID;b.Asc.plugin._initInternal=!0;b.parent.postMessage(JSON.stringify(d),"*")}};a.send()}};b.Asc.supportOrigins={};b.Asc.supportOrigins[b.origin]=!0;b.addEventListener?b.addEventListener("message",l,!1):b.attachEvent("onmessage",l);b.Asc.plugin._attachCustomMenuClickEvent=function(a,
d,f){this[a]||(this[a]={});this[a][d]=f};b.Asc.plugin._onCustomMenuClick=function(a,d){var f=p,c=d.indexOf("_oo_sep_");-1!==c&&(f=d.substring(c+8),d=d.substring(0,c));this[a]&&this[a][d]&&this[a][d].call(this,f)};b.Asc.plugin.attachContextMenuClickEvent=function(a,d){this._attachCustomMenuClickEvent("contextMenuEvents",a,d)};b.Asc.plugin.event_onContextMenuClick=function(a){this._onCustomMenuClick("contextMenuEvents",a)};b.Asc.plugin.attachToolbarMenuClickEvent=function(a,d){this._attachCustomMenuClickEvent("toolbarMenuEvents",
a,d)};b.Asc.plugin.event_onToolbarMenuClick=function(a){this._onCustomMenuClick("toolbarMenuEvents",a)};b.Asc.plugin.attachEvent=function(a,d){var f=b.Asc.plugin;f._events||(f._events={});f._events[a]=d};b.Asc.plugin.detachEvent=function(a){var d=b.Asc.plugin;d._events&&d._events[a]&&delete d._events[a]};b.Asc.plugin.onEvent=function(a,d){var f=b.Asc.plugin;f._events&&f._events[a]&&f._events[a].call(f,d)};b.Asc.plugin.attachEditorEvent=function(a,d){b.Asc.plugin["event_"+a]=d.bind(b.Asc.plugin);r(JSON.stringify({guid:b.Asc.plugin.guid,
type:"attachEvent",name:a}))};b.Asc.plugin.detachEditorEvent=function(a){b.Asc.plugin["event_"+a]&&delete b.Asc.plugin["event_"+a];r(JSON.stringify({guid:b.Asc.plugin.guid,type:"detachEvent",name:a}))};b.onunload=function(){b.addEventListener?b.removeEventListener("message",l,!1):b.detachEvent("onmessage",l)}})(window,void 0);
(function(b,p){function r(){function c(){return(65536+e[h++]).toString(16).substring(1)}if(!b.crypto||!b.crypto.getRandomValues){function g(){return Math.floor(65536*(1+Math.random())).toString(16).substring(1)}return g()+g()+"-"+g()+"-"+g()+"-"+g()+"-"+g()+g()+g()}var e=new Uint16Array(8);b.crypto.getRandomValues(e);var h=0;return c()+c()+"-"+c()+"-"+c()+"-"+c()+"-"+c()+c()+c()}function n(c){return b.Asc.plugin.tr(c)}function m(c,e){this.itemType=f.None;this.editors=["word","cell","slide"];this.id=
e===p?r():e;this.icons=null;this.text="";this.hint=null;this.data="";this.separator=!1;this.lockInViewMode=!0;this.disabled=this.enableToggle=!1;this.parent=c?c:null;this.childs=null;this.parent&&(this.parent.childs||(this.parent.childs=[]),this.parent.childs.push(this))}function k(c,e){m.call(this,c,e);this.itemType=f.ContextMenu;this.showOnOptionsType=[];a.Buttons.ButtonsContextMenu.push(this)}function l(c,e){m.call(this,c,e);this.itemType=f.Toolbar;this.type=d.BigButton;this.tab="";a.Buttons.ButtonsToolbar.push(this)}
b.Asc=b.Asc||{};var a=b.Asc;a.Buttons={};a.Buttons.ButtonsContextMenu=[];a.Buttons.ButtonsToolbar=[];a.Buttons.registerContextMenu=function(){b.Asc.plugin.attachEvent("onContextMenuShow",function(c){if(c){var e={guid:b.Asc.plugin.guid};for(let h=0,g=a.Buttons.ButtonsContextMenu.length;h<g;h++){let q=a.Buttons.ButtonsContextMenu[h];if(null===q.parent)q.onContextMenuShow(c,e)}e.items&&b.Asc.plugin.executeMethod("AddContextMenuItem",[e])}})};a.Buttons.registerToolbarMenu=function(){let c={guid:b.Asc.plugin.guid,
tabs:[]};for(let e=0,h=a.Buttons.ButtonsToolbar.length;e<h;e++){let g=a.Buttons.ButtonsToolbar[e];null===g.parent&&g.toToolbar(c);if(g.menu)for(item of g.menu)item.onclick&&b.Asc.plugin.attachToolbarMenuClickEvent(item.id,item.onclick)}0<c.tabs.length&&b.Asc.plugin.executeMethod("AddToolbarMenuItem",[c])};var d={Button:"button",BigButton:"big-button"},f={None:0,ContextMenu:1,Toolbar:2};m.prototype.toItem=function(){let c={id:this.id,text:n(this.text)};null!==this.hint&&(c.hint=n(""===this.hint?this.hint:
this.text));this.separator&&(c.separator=!0);this.data&&(c.data=this.data);this.lockInViewMode&&(c.lockInViewMode=!0);this.enableToggle&&(c.enableToggle=!0);this.disabled&&(c.disabled=!0);this.icons&&(c.icons=this.icons);this.itemType===f.Toolbar&&(c.type=this.type);this.menu&&(c.items=this.menu.map(function(e){e.text=n(e.text);return e}));this.split&&(c.split=!0);return c};m.prototype.attachOnClick=function(c){};m.prototype.onClick=function(){console.log("BUTTON: "+this.text)};k.prototype=Object.create(m.prototype);
k.prototype.constructor=k;k.prototype.copy=function(){let c=new k(this.parent,this.id);c.editors=this.editors;c.separator=this.separator;c.lockInViewMode=this.lockInViewMode;c.enableToggle=this.enableToggle;c.disabled=this.disabled;c.showOnOptionsType=this.showOnOptionsType.slice();return c};k.prototype.addCheckers=function(){let c=arguments.length;this.showOnOptionsType=Array(c);for(let e=0;e<c;e++)this.showOnOptionsType[e]=arguments[e]};k.prototype.attachOnClick=function(c){b.Asc.plugin.attachContextMenuClickEvent(this.id,
c)};k.prototype.onContextMenuShowAnalyze=function(c,e){return!1};k.prototype.onContextMenuShowExtendItem=function(c,e){};k.prototype.onContextMenuShow=function(c,e){if(!this.onContextMenuShowAnalyze(c,e)){var h=!1;for(let g=0,q=this.editors.length;g<q;g++)if(a.plugin.info.editorType===this.editors[g]){h=!0;break}if(h)for(let g=0,q=this.showOnOptionsType.length;g<q;g++)if(c.type===this.showOnOptionsType[g]||"All"===this.showOnOptionsType[g]){e.items||(e.items=[]);h=this.toItem();this.onContextMenuShowExtendItem(c,
h);if(this.childs)for(let t=0,u=this.childs.length;t<u;t++)this.childs[t].onContextMenuShow(c,h);e.items.push(h);break}}};l.prototype=Object.create(m.prototype);l.prototype.constructor=l;l.prototype.attachOnClick=function(c){b.Asc.plugin.attachToolbarMenuClickEvent(this.id,c)};l.prototype.toItem=function(c){c=m.prototype.toItem.call(this);c.type=this.type;return c};l.prototype.toToolbar=function(c){if(null===this.parent){var e={id:this.id,text:n(this.text),items:[]};null!==this.hint&&(e.hint=n(""===
this.hint?this.hint:this.text));c.tabs.push(e)}else e=this.toItem(),c.items||(c.items=[]),c.items.push(e);if(this.childs)for(let h=0,g=this.childs.length;h<g;h++)this.childs[h].toToolbar(e)};a.ToolbarButtonType=d;a.ButtonContextMenu=k;a.ButtonToolbar=l})(window);
