/*
 * (c) Copyright Ascensio System SIA 2010
 *
 * This program is a free software product. You can redistribute it and/or
 * modify it under the terms of the GNU Affero General Public License (AGPL)
 * version 3 as published by the Free Software Foundation. In accordance with
 * Section 7(a) of the GNU AGPL its Section 15 shall be amended to the effect
 * that Ascensio System SIA expressly excludes the warranty of non-infringement
 * of any third-party rights.
 *
 * This program is distributed WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR  PURPOSE. For
 * details, see the GNU AGPL at: http://www.gnu.org/licenses/agpl-3.0.html
 *
 * You can contact Ascensio System SIA at 20A-6 Ernesta Birznieka-Upish
 * street, Riga, Latvia, EU, LV-1050.
 *
 * The  interactive user interfaces in modified source and object code versions
 * of the Program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU AGPL version 3.
 *
 * Pursuant to Section 7(b) of the License you must retain the original Product
 * logo when distributing the program. Pursuant to Section 7(e) we decline to
 * grant you any rights under trademark law for use of our trademarks.
 *
 * All the Product's GUI elements, including illustrations and icon sets, as
 * well as technical writing content are licensed under the terms of the
 * Creative Commons Attribution-ShareAlike 4.0 International. See the License
 * terms at http://creativecommons.org/licenses/by-sa/4.0/legalcode
 *
 */

(function(b,v){function y(c){b.Asc.plugin.ie_channel?b.Asc.plugin.ie_channel.postMessage(c):b.parent.postMessage(c,"*")}function u(c,f){if(!c||"object"!=typeof c&&"array"!=typeof c)return c;f=f===v?{}:f;for(var e in c)c.hasOwnProperty(e)&&(f[e]=c[e]&&"object"===typeof c[e]?u(c[e]):c[e]);return f}function n(c){var f=b.location.search,e=c+"=";c=f.indexOf(e);return 0<=c?(c+=e.length,e=f.indexOf("&",c),0>e&&(e=f.length),f.substring(c,e)):v}function p(){var c=n("windowID");c&&(b.Asc.plugin.windowID=c,
b.Asc.plugin.guid||(b.Asc.plugin.guid=decodeURIComponent(n("guid"))));return v!==c?!0:!1}function q(c){if(b.Asc&&b.Asc.plugin)if(b.plugin_onMessage)b.Asc.supportOrigins[c.origin]&&b.plugin_onMessage(c);else if(b.Asc.plugin._initInternal&&"string"==typeof c.data){var f={};try{f=JSON.parse(c.data)}catch(e){f={}}"plugin_init"==f.type&&(b.Asc.supportOrigins[c.origin]=!0,b.Asc.plugin.ie_channel_check(c),eval(f.data))}}b.Asc=b.Asc||{};b.Asc.plugin={};b.Asc.plugin.ie_channel=null;b.Asc.plugin.ie_channel_check=
function(c){var f=navigator.userAgent.toLowerCase();(-1<f.indexOf("msie")||-1<f.indexOf("trident"))&&c.ports&&c.ports[0]&&(this.ie_channel=c.ports[0])};b.Asc.plugin.tr_init=!1;b.Asc.plugin.tr=function(c){return c};b.Asc.scope={};b.Asc.scope.prototype={clear:function(){for(var c in b.Asc.scope)delete b.Asc.scope[c]}};b.onload=function(){if(b.Asc&&b.Asc.plugin){var c=new XMLHttpRequest;c.open("get","./config.json",!0);c.responseType="json";c.onload=function(){if(b.Asc&&b.Asc.plugin){if(404===c.status)return c.onerror();
if(200==c.status||0==c.status&&4==c.readyState){var f=c.response;"string"==typeof f&&(f=JSON.parse(f));u(f,b.Asc.plugin);f={type:"initialize",guid:b.Asc.plugin.guid};p()&&(f.windowID=b.Asc.plugin.windowID);var e=document.body;e&&!0!==b.Asc.plugin.enableDrops&&(e.ondrop=function(m){m&&m.preventDefault&&m.preventDefault();return!1},e.ondragenter=function(m){m&&m.preventDefault&&m.preventDefault();return!1},e.ondragover=function(m){m&&m.preventDefault&&m.preventDefault();m&&m.dataTransfer&&(m.dataTransfer.dropEffect=
"none");return!1});b.Asc.plugin._initInternal=!0;b.parent.postMessage(JSON.stringify(f),"*")}}};c.onerror=function(){if(b.Asc&&b.Asc.plugin&&p()){var f={type:"initialize",guid:b.Asc.plugin.guid};f.windowID=b.Asc.plugin.windowID;b.Asc.plugin._initInternal=!0;b.parent.postMessage(JSON.stringify(f),"*")}};c.send()}};b.Asc.supportOrigins={};b.Asc.supportOrigins[b.origin]=!0;b.addEventListener?b.addEventListener("message",q,!1):b.attachEvent("onmessage",q);b.Asc.plugin._attachCustomMenuClickEvent=function(c,
f,e){this[c]||(this[c]={});this[c][f]=e};b.Asc.plugin._onCustomMenuClick=function(c,f){var e=v,m=f.indexOf("_oo_sep_");-1!==m&&(e=f.substring(m+8),f=f.substring(0,m));this[c]&&this[c][f]&&this[c][f].call(this,e)};b.Asc.plugin.attachContextMenuClickEvent=function(c,f){this._attachCustomMenuClickEvent("contextMenuEvents",c,f)};b.Asc.plugin.event_onContextMenuClick=function(c){this._onCustomMenuClick("contextMenuEvents",c)};b.Asc.plugin.attachToolbarMenuClickEvent=function(c,f){this._attachCustomMenuClickEvent("toolbarMenuEvents",
c,f)};b.Asc.plugin.event_onToolbarMenuClick=function(c){this._onCustomMenuClick("toolbarMenuEvents",c)};b.Asc.plugin.attachWindowHeaderMenuClickEvent=function(c,f){this._attachCustomMenuClickEvent("windowHeaderMenuEvents",c,f)};b.Asc.plugin.event_onWindowHeaderMenuClick=function(c){this._onCustomMenuClick("windowHeaderMenuEvents",c)};b.Asc.plugin.attachEvent=function(c,f){var e=b.Asc.plugin;e._events||(e._events={});e._events[c]=f};b.Asc.plugin.detachEvent=function(c){var f=b.Asc.plugin;f._events&&
f._events[c]&&delete f._events[c]};b.Asc.plugin.onEvent=function(c,f){var e=b.Asc.plugin;e._events&&e._events[c]&&e._events[c].call(e,f)};b.Asc.plugin.attachEditorEvent=function(c,f){b.Asc.plugin["event_"+c]=f.bind(b.Asc.plugin);y(JSON.stringify({guid:b.Asc.plugin.guid,type:"attachEvent",name:c}))};b.Asc.plugin.detachEditorEvent=function(c){b.Asc.plugin["event_"+c]&&delete b.Asc.plugin["event_"+c];y(JSON.stringify({guid:b.Asc.plugin.guid,type:"detachEvent",name:c}))};b.onunload=function(){b.addEventListener?
b.removeEventListener("message",q,!1):b.detachEvent("onmessage",q)}})(window,void 0);
(function(b,v){function y(){function a(){return(65536+d[h++]).toString(16).substring(1)}if(!b.crypto||!b.crypto.getRandomValues){function g(){return Math.floor(65536*(1+Math.random())).toString(16).substring(1)}return g()+g()+"-"+g()+"-"+g()+"-"+g()+"-"+g()+g()+g()}var d=new Uint16Array(8);b.crypto.getRandomValues(d);var h=0;return a()+a()+"-"+a()+"-"+a()+"-"+a()+"-"+a()+a()+a()}function u(a){return b.Asc.plugin.tr(a)}function n(a,d){this.itemType=w.None;this.editors=["word","cell","slide"];this.id=
d===v?y():d;this.icons=null;this.text="";this.hint=null;this.data="";this.separator=!1;this.lockInViewMode=!0;this.removed=this.disabled=this.enableToggle=!1;this.parent=a?a:null;this.childs=null;this.parent&&(this.parent.childs||(this.parent.childs=[]),this.parent.childs.push(this))}function p(a,d){n.call(this,a,d);this.itemType=w.ContextMenu;this.showOnOptionsType=[];e.Buttons.ButtonsContextMenu.push(this)}function q(a,d){n.call(this,a,d);this.itemType=w.Toolbar;this.type=m.BigButton;this.tab="";
e.Buttons.ButtonsToolbar.push(this)}function c(a,d){n.call(this,a,d);this.itemType=w.ContentControl;this.checker=null;0===e.Buttons.ButtonsContentControl.length&&e.Buttons.registerContentControl();e.Buttons.ButtonsContentControl.push(this)}function f(a,d){n.call(this,a,d);this.itemType=w.WindowHeader;this.align="right";this.isTitle=!1;e.Buttons.ButtonsWindowHeader.push(this)}b.Asc=b.Asc||{};var e=b.Asc;e.Buttons={};e.Buttons.ButtonsContextMenu=[];e.Buttons.ButtonsToolbar=[];e.Buttons.ButtonsContentControl=
[];e.Buttons.ButtonsWindowHeader=[];e.Buttons.registerContextMenu=function(){b.Asc.plugin.attachEvent("onContextMenuShow",function(a){if(a){var d={guid:b.Asc.plugin.guid};for(let h=0,g=e.Buttons.ButtonsContextMenu.length;h<g;h++){let l=e.Buttons.ButtonsContextMenu[h];if(null===l.parent)l.onContextMenuShow(a,d)}d.items&&b.Asc.plugin.executeMethod("AddContextMenuItem",[d])}})};e.Buttons.registerToolbarMenu=function(){let a={guid:b.Asc.plugin.guid,tabs:[]};for(let d=0,h=e.Buttons.ButtonsToolbar.length;d<
h;d++){let g=e.Buttons.ButtonsToolbar[d];null===g.parent&&g.toToolbar(a);if(g.menu)for(let l in g.menu){let k=g.menu.hasOwnProperty(l)?g.menu[l]:null;k&&k.onclick&&b.Asc.plugin.attachToolbarMenuClickEvent(k.id,k.onclick)}}0<a.tabs.length&&b.Asc.plugin.executeMethod("AddToolbarMenuItem",[a])};e.Buttons.updateToolbarMenu=function(a,d,h){a=new e.ButtonToolbar(null,a);a.text=d;d={guid:b.Asc.plugin.guid,tabs:[]};a.childs=h;for(let g=0,l=h.length;g<l;g++)h[g].parent=a;a.toToolbar(d);for(let g=0,l=h.length;g<
l;g++)if(a=h[g],a.menu)for(let k in a.menu){let r=a.menu.hasOwnProperty(k)?a.menu[k]:null;r&&r.onclick&&b.Asc.plugin.attachToolbarMenuClickEvent(r.id,r.onclick)}0<d.tabs.length&&b.Asc.plugin.executeMethod("UpdateToolbarMenuItem",[d])};e.Buttons.registerWindowHeader=function(a,d){e.Buttons.updateWindowHeader(a,d,!0)};e.Buttons.updateWindowHeader=function(a,d,h){a={guid:b.Asc.plugin.guid,frames:[{id:a,items:[]}]};for(let g=0,l=d.length;g<l;g++){let k=d[g];k.parent=null;k.toWindowHeader(a.frames[0]);
if(k.menu)for(let r in k.menu){let t=k.menu.hasOwnProperty(r)?k.menu[r]:null;t&&t.onclick&&b.Asc.plugin.attachWindowHeaderMenuClickEvent(t.id,t.onclick)}}0<a.frames[0].items.length&&b.Asc.plugin.executeMethod(h?"AddWindowHeaderItem":"UpdateWindowHeaderItem",[a])};e.Buttons.registerContentControl=function(){b.Asc.plugin.attachEditorEvent("onShowContentControlTrack",function(d){let h={guid:b.Asc.plugin.guid,items:{}},g=[];for(let l=0,k=e.Buttons.ButtonsContentControl.length;l<k;++l)g.push(e.Buttons.ButtonsContentControl[l].onShowTrack(d,
h.items));Promise.all(g).then(function(){for(let l in h.items){b.Asc.plugin.executeMethod("AddContentControlButtons",[h]);break}})});b.Asc.plugin._attachContentControlButtonClickEvent=function(d,h){this.ContentControlButtonEvents||(this.ContentControlButtonEvents={});this.ContentControlButtonEvents[d]=h};let a=b.Asc.plugin;b.Asc.plugin.attachEditorEvent("onContentControlButtonClick",function(d){let h=d&&d.buttonId?d.buttonId:null;d=d&&d.contentControlId?d.contentControlId:null;h&&d&&a.ContentControlButtonEvents&&
a.ContentControlButtonEvents[h]&&a.ContentControlButtonEvents[h].call(a,d)})};var m={Button:"button",BigButton:"big-button"},w={None:0,ContextMenu:1,Toolbar:2,ContentControl:3,WindowHeader:4};n.prototype.toItem=function(){let a={id:this.id,text:u(this.text)};null!==this.hint&&(a.hint=u(""===this.hint?this.hint:this.text));this.separator&&(a.separator=!0);this.data&&(a.data=this.data);this.lockInViewMode&&(a.lockInViewMode=!0);this.enableToggle&&(a.enableToggle=!0);a.disabled=this.disabled?!0:!1;"pressed"in
this&&(a.pressed=!!this.pressed);this.removed&&(a.removed=!0);this.icons&&(a.icons=this.icons);this.itemType===w.Toolbar&&(a.type=this.type);this.menu&&(a.items=this.menu.map(function(d){d.text=u(d.text);return d}));this.split&&(a.split=!0);return a};n.prototype.attachOnClick=function(a){};n.prototype.onClick=function(){console.log("BUTTON: "+this.text)};p.prototype=Object.create(n.prototype);p.prototype.constructor=p;p.prototype.copy=function(){let a=new p(this.parent,this.id);a.editors=this.editors;
a.separator=this.separator;a.lockInViewMode=this.lockInViewMode;a.enableToggle=this.enableToggle;a.disabled=this.disabled;a.showOnOptionsType=this.showOnOptionsType.slice();return a};p.prototype.addCheckers=function(){let a=arguments.length;this.showOnOptionsType=Array(a);for(let d=0;d<a;d++)this.showOnOptionsType[d]=arguments[d]};p.prototype.attachOnClick=function(a){b.Asc.plugin.attachContextMenuClickEvent(this.id,a)};p.prototype.onContextMenuShowAnalyze=function(a,d){return!1};p.prototype.onContextMenuShowExtendItem=
function(a,d){};p.prototype.onContextMenuShow=function(a,d){if(!this.onContextMenuShowAnalyze(a,d)){var h=!1;for(let g=0,l=this.editors.length;g<l;g++)if(e.plugin.info.editorType===this.editors[g]){h=!0;break}if(h)for(let g=0,l=this.showOnOptionsType.length;g<l;g++)if(a.type===this.showOnOptionsType[g]||"All"===this.showOnOptionsType[g]){d.items||(d.items=[]);h=this.toItem();this.onContextMenuShowExtendItem(a,h);if(this.childs)for(let k=0,r=this.childs.length;k<r;k++)this.childs[k].onContextMenuShow(a,
h);d.items.push(h);break}}};q.prototype=Object.create(n.prototype);q.prototype.constructor=q;q.prototype.attachOnClick=function(a){b.Asc.plugin.attachToolbarMenuClickEvent(this.id,a)};q.prototype.toItem=function(a){a=n.prototype.toItem.call(this);a.type=this.type;return a};q.prototype.toToolbar=function(a){if(null===this.parent){var d={id:this.id,text:u(this.text),items:[]};null!==this.hint&&(d.hint=u(""===this.hint?this.hint:this.text));a.tabs.push(d)}else d=this.toItem(),a.items||(a.items=[]),a.items.push(d);
if(this.childs)for(let h=0,g=this.childs.length;h<g;h++)this.childs[h].toToolbar(d)};c.prototype=Object.create(n.prototype);c.prototype.constructor=c;c.prototype.attachOnClick=function(a){b.Asc.plugin._attachContentControlButtonClickEvent(this.id,a)};c.prototype.addChecker=function(a){a&&"function"===typeof a&&(this.checker=a)};c.prototype.onShowTrack=function(a,d){let h=this.checker,g=[],l=this.toItem();for(let k=0,r=a.length;k<r;++k){let t=a[k];g.push((new Promise(function(x){if(h){let z=h(t);z instanceof
Promise?z.then(function(A){x(A)}):x(!!z)}else x(!0)})).then(function(x){x&&(d[t]||(d[t]=[]),d[t].push(l))}))}return Promise.all(g)};f.prototype=Object.create(n.prototype);f.prototype.constructor=f;f.prototype.attachOnClick=function(a){b.Asc.plugin.attachWindowHeaderMenuClickEvent(this.id,a)};f.prototype.toItem=function(){let a=n.prototype.toItem.call(this);a.type="button";this.align&&(a.align=this.align);this.isTitle&&(a.isTitle=!0);return a};f.prototype.toWindowHeader=function(a){let d=this.toItem();
a.items||(a.items=[]);a.items.push(d);if(this.childs)for(let h=0,g=this.childs.length;h<g;h++)this.childs[h].toWindowHeader(d)};e.ToolbarButtonType=m;e.ButtonContextMenu=p;e.ButtonToolbar=q;e.ButtonContentControl=c;e.ButtonWindowHeader=f})(window);
