    var oDocument = Api.GetDocument();
    var oSection = oDocument.GetFinalSection();
    var oHeading1Style = oDocument.CreateStyle("Heading 1", "paragraph");
    var oParaPr = oHeading1Style.GetParaPr();
    oSection.SetPageMargins(800, 300, 800, 300);
    oParaPr.SetKeepNext(true);
    oParaPr.SetKeepLines(true);
    oParaPr.SetSpacingAfter(40);
    var oTextPr = oHeading1Style.GetTextPr();
    oTextPr.SetFontSize(30);
    oTextPr.SetFontFamily("Calibri Light");
    var oParagraph = oDocument.GetElement(0);
    oParagraph = Api.CreateParagraph();
    oParagraph.SetStyle(oHeading1Style);
    oParagraph.AddText("姓名（英文名）");
    oParagraph.SetBold(true);
    oParagraph.SetJc( "center" ); 
    oDocument.Push(oParagraph);
    oParagraph = Api.CreateParagraph();
    oParagraph.SetStyle(oHeading1Style);
    oParagraph.AddText("xxx-xxxx-xxxx | xxxxxxxxxxx@xxx.com");
    oParagraph.SetJc( "center" ); 
    oParagraph.SetFontSize(20);
    oDocument.Push(oParagraph);
    oParagraph = Api.CreateParagraph();
    oParagraph.SetStyle(oHeading1Style);
    oParagraph.AddText("学校 专业");
    oParagraph.SetJc( "center" ); 
    oParagraph.SetFontSize(20);
    oDocument.Push(oParagraph);
    oParagraph = Api.CreateParagraph();
    oParagraph.AddText("个人总结");
    oParagraph.SetBold(true);
    oParagraph.SetJc( "left" ); 
    oParagraph.SetFontSize(25);
    oParagraph.SetSpacingBefore(200);
    oParagraph.SetSpacingAfter(0);
    oParagraph.SetFontFamily("Consolas");
    oDocument.Push(oParagraph);
    oParagraph = Api.CreateParagraph();
    oParagraph.AddText("——————————————————————————————————————————————————————————————————————————");
    oParagraph.SetJc( "left" ); 
    oParagraph.SetFontSize(25);
    oParagraph.SetSpacingAfter(0);
    oParagraph.SetFontFamily("Consolas");
    oDocument.Push(oParagraph);
    var oDrawing =Api.CreateImage("https://legacy-api.onlyoffice.com/content/img/docbuilder/examples/api-word.jpg", 22 * 36000, 35 * 36000);
    oDrawing.SetWrappingStyle("behind");
    oDrawing.SetHorPosition("leftMargin", 6000000);
    oDrawing.SetVerPosition("topMargin", 200000);
    oParagraph.AddDrawing(oDrawing);
    var oParagraph = Api.CreateParagraph();
    oParagraph.AddText("（经历较少的学生、转行和工作多年的人适合填写该模板，呈现与申请岗位相关的经验和优势）");
    oDocument.Push(oParagraph);
    oParagraph = Api.CreateParagraph();
    oParagraph.AddText("教育经历");
    oParagraph.SetBold(true);
    oParagraph.SetJc( "left" ); 
    oParagraph.SetFontSize(25);
    oParagraph.SetSpacingBefore(200);
    oParagraph.SetSpacingAfter(0);
    oParagraph.SetFontFamily("Consolas");
    oDocument.Push(oParagraph);
    oParagraph = Api.CreateParagraph();
    oParagraph.AddText("——————————————————————————————————————————————————————————————————————————");
    oParagraph.SetJc( "left" ); 
    oParagraph.SetFontSize(25);
    oParagraph.SetSpacingAfter(0);
    oParagraph.SetFontFamily("Consolas");
    oDocument.Push(oParagraph);
    var oParagraph = Api.CreateParagraph();
    oParagraph.AddText("（教育经历是HR会关注的部分（尤其是学生简历），其中学校、专业、毕业时间是必填项）");
    oDocument.Push(oParagraph);
    var oParagraph = Api.CreateParagraph();
    var oRun = Api.CreateRun();
    oRun.AddText("xx大学");
    oRun.SetBold(true);
    oParagraph.AddElement(oRun);
    oRun = Api.CreateRun();
    oRun.AddText("-计算机科学与技术专业 本科 计算机学院");
    oParagraph.AddElement(oRun);
    oRun = Api.CreateRun();
    oRun.AddText("2018年9月 - 2022年6月");
    oParagraph.AddElement(oRun);
    oDocument.Push(oParagraph);
    var oNumbering = oDocument.CreateNumbering("bullet");
    var oNumLvl = oNumbering.GetLevel(0);
    var oParagraph = Api.CreateParagraph();
    oParagraph.AddText("GPA：xxx(专业前x%)");
    oParagraph.SetNumbering(oNumLvl);
    oParagraph.SetContextualSpacing(true);
    oDocument.Push(oParagraph);
    var oNumbering = oDocument.CreateNumbering("bullet");
    var oNumLvl = oNumbering.GetLevel(0);
    var oParagraph = Api.CreateParagraph();
    oParagraph.AddText("相关课程：");
    oParagraph.SetNumbering(oNumLvl);
    oParagraph.SetContextualSpacing(true);
    oDocument.Push(oParagraph);
    oParagraph = Api.CreateParagraph();
    oParagraph.AddText("荣誉奖项");
    oParagraph.SetBold(true);
    oParagraph.SetJc( "left" ); 
    oParagraph.SetFontSize(25);
    oParagraph.SetSpacingBefore(200);
    oParagraph.SetSpacingAfter(0);
    oParagraph.SetFontFamily("Consolas");
    oDocument.Push(oParagraph);
    oParagraph = Api.CreateParagraph();
    oParagraph.AddText("——————————————————————————————————————————————————————————————————————————");
    oParagraph.SetJc( "left" ); 
    oParagraph.SetFontSize(25);
    oParagraph.SetSpacingAfter(0);
    oParagraph.SetFontFamily("Consolas");
    oDocument.Push(oParagraph);
    var oParagraph = Api.CreateParagraph();
    oParagraph.AddText("（含金量高的奖项是很好的加分项）");
    oDocument.Push(oParagraph);
    oParagraph = Api.CreateParagraph();
    oParagraph.AddText("项目经历");
    oParagraph.SetBold(true);
    oParagraph.SetJc( "left" ); 
    oParagraph.SetFontSize(25);
    oParagraph.SetSpacingBefore(200);
    oParagraph.SetSpacingAfter(0);
    oParagraph.SetFontFamily("Consolas");
    oDocument.Push(oParagraph);
    oParagraph = Api.CreateParagraph();
    oParagraph.AddText("——————————————————————————————————————————————————————————————————————————");
    oParagraph.SetJc( "left" ); 
    oParagraph.SetFontSize(25);
    oParagraph.SetSpacingAfter(0);
    oParagraph.SetFontFamily("Consolas");
    oDocument.Push(oParagraph);
    var oNumbering = oDocument.CreateNumbering("bullet");
    oParagraph.AddText("（介绍课内或课外项目、展示对某个领域或某种技能的学握程度）");
    oDocument.Push(oParagraph);
    oParagraph = Api.CreateParagraph();
    oParagraph.AddText("校园经历");
    oParagraph.SetBold(true);
    oParagraph.SetJc( "left" ); 
    oParagraph.SetFontSize(25);
    oParagraph.SetSpacingBefore(200);
    oParagraph.SetSpacingAfter(0);
    oParagraph.SetFontFamily("Consolas");
    oDocument.Push(oParagraph);
    oParagraph = Api.CreateParagraph();
    oParagraph.AddText("——————————————————————————————————————————————————————————————————————————");
    oParagraph.SetJc( "left" ); 
    oParagraph.SetFontSize(25);
    oParagraph.SetSpacingAfter(0);
    oParagraph.SetFontFamily("Consolas");
    oDocument.Push(oParagraph);
    var oParagraph = Api.CreateParagraph();
    oParagraph.AddText("（可以反映学生在学习能力之外的优势，比如社交能力、组织领导能力、沟通协作能力、应变能力等）");
    oDocument.Push(oParagraph);
    oParagraph = Api.CreateParagraph();
    oParagraph.AddText("技能和其他");
    oParagraph.SetBold(true);
    oParagraph.SetJc( "left" ); 
    oParagraph.SetFontSize(25);
    oParagraph.SetSpacingBefore(200);
    oParagraph.SetSpacingAfter(0);
    oParagraph.SetFontFamily("Consolas");
    oDocument.Push(oParagraph);
    oParagraph = Api.CreateParagraph();
    oParagraph.AddText("——————————————————————————————————————————————————————————————————————————");
    oParagraph.SetJc( "left" ); 
    oParagraph.SetFontSize(25);
    oParagraph.SetSpacingAfter(0);
    oParagraph.SetFontFamily("Consolas");
    oDocument.Push(oParagraph);
    var oParagraph = Api.CreateParagraph();
    oParagraph.AddText("（突出掌握的技能和证书）");
    oDocument.Push(oParagraph);
    var oNumbering = oDocument.CreateNumbering("bullet");
    var oNumLvl = oNumbering.GetLevel(0);
    var oParagraph = Api.CreateParagraph();
    var oRun = Api.CreateRun();
    oRun.AddText("语言：");
    oRun.SetBold(true);
    oParagraph.AddElement(oRun);
    oRun = Api.CreateRun();
    oRun.AddText("");
    oParagraph.AddElement(oRun);
    oParagraph.SetNumbering(oNumLvl);
    oParagraph.SetContextualSpacing(true);
    oDocument.Push(oParagraph);
    var oNumbering = oDocument.CreateNumbering("bullet");
    var oNumLvl = oNumbering.GetLevel(0);
    var oParagraph = Api.CreateParagraph();
    var oRun = Api.CreateRun();
    oRun.AddText("技能：");
    oRun.SetBold(true);
    oParagraph.AddElement(oRun);
    oRun = Api.CreateRun();
    oRun.AddText("");
    oParagraph.AddElement(oRun);
    oParagraph.SetNumbering(oNumLvl);
    oParagraph.SetContextualSpacing(true);
    oDocument.Push(oParagraph);
    var oNumbering = oDocument.CreateNumbering("bullet");
    var oNumLvl = oNumbering.GetLevel(0);
    var oParagraph = Api.CreateParagraph();
    var oRun = Api.CreateRun();
    oRun.AddText("证书/培训：");
    oRun.SetBold(true);
    oParagraph.AddElement(oRun);
    oRun = Api.CreateRun();
    oRun.AddText("");
    oParagraph.AddElement(oRun);
    oParagraph.SetNumbering(oNumLvl);
    oParagraph.SetContextualSpacing(true);
    oDocument.Push(oParagraph);
    var oNumbering = oDocument.CreateNumbering("bullet");
    var oNumLvl = oNumbering.GetLevel(0);
    var oParagraph = Api.CreateParagraph();
    var oRun = Api.CreateRun();
    oRun.AddText("兴趣爱好：");
    oRun.SetBold(true);
    oParagraph.AddElement(oRun);
    oRun = Api.CreateRun();
    oRun.AddText("");
    oParagraph.AddElement(oRun);
    oParagraph.SetNumbering(oNumLvl);
    oParagraph.SetContextualSpacing(true);
    oDocument.Push(oParagraph);
