/*
 * (c) Copyright Ascensio System SIA 2010
 *
 * This program is a free software product. You can redistribute it and/or
 * modify it under the terms of the GNU Affero General Public License (AGPL)
 * version 3 as published by the Free Software Foundation. In accordance with
 * Section 7(a) of the GNU AGPL its Section 15 shall be amended to the effect
 * that Ascensio System SIA expressly excludes the warranty of non-infringement
 * of any third-party rights.
 *
 * This program is distributed WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR  PURPOSE. For
 * details, see the GNU AGPL at: http://www.gnu.org/licenses/agpl-3.0.html
 *
 * You can contact Ascensio System SIA at 20A-6 Ernesta Birznieka-Upish
 * street, Riga, Latvia, EU, LV-1050.
 *
 * The  interactive user interfaces in modified source and object code versions
 * of the Program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU AGPL version 3.
 *
 * Pursuant to Section 7(b) of the License you must retain the original Product
 * logo when distributing the program. Pursuant to Section 7(e) we decline to
 * grant you any rights under trademark law for use of our trademarks.
 *
 * All the Product's GUI elements, including illustrations and icon sets, as
 * well as technical writing content are licensed under the terms of the
 * Creative Commons Attribution-ShareAlike 4.0 International. See the License
 * terms at http://creativecommons.org/licenses/by-sa/4.0/legalcode
 *
 */

const ThemeDefaultMessage = {
    "type": "Theme",
    "theme": {
        "Name": "theme-white",
        "Type": "light",
        "RulersButton": false,
        "NavigationButtons": false,
        "BackgroundColor": "#F3F3F3",
        "PageOutline": "#CBCBCB",
        "RulerDark": "#E1E1E1",
        "RulerLight": "#FFFFFF",
        "RulerOutline": "#CBCBCB",
        "RulerMarkersOutlineColor": "#585858",
        "RulerMarkersOutlineColorOld": "#B2B2B2",
        "RulerMarkersFillColor": "#FFFFFF",
        "RulerMarkersFillColorOld": "#FFFFFF",
        "RulerTextColor": "#585858",
        "RulerTabsColor": "#222222",
        "RulerTabsColorOld": "#686868",
        "RulerTableColor1": "#FFFFFF",
        "RulerTableColor2": "#585858",
        "ScrollBackgroundColor": "#F3F3F3",
        "ScrollOutlineColor": "#CBCBCB",
        "ScrollOutlineHoverColor": "#B2B2B2",
        "ScrollOutlineActiveColor": "#949494",
        "ScrollerColor": "#F3F3F3",
        "ScrollerHoverColor": "#000000",
        "ScrollerActiveColor": "#000000",
        "ScrollArrowColor": "#949494",
        "ScrollArrowHoverColor": "#7F7F7F",
        "ScrollArrowActiveColor": "#686868",
        "ScrollerTargetColor": "#949494",
        "ScrollerTargetHoverColor": "#7F7F7F",
        "ScrollerTargetActiveColor": "#686868",
        "STYLE_THUMBNAIL_WIDTH": 104,
        "STYLE_THUMBNAIL_HEIGHT": 40,
        "isNeedInvertOnActive": false,
        "ContentControlsBack": "#F1F1F1",
        "ContentControlsHover": "#D8DADC",
        "ContentControlsActive": "#7C838A",
        "ContentControlsText": "#444444",
        "ContentControlsTextActive": "#FFFFFF",
        "ContentControlsAnchorActive": "#CFCFCF",
        "FormsContentControlsOutlineHover": "rgba(0, 0, 0, 0.3)",
        "FormsContentControlsOutlineActive": "rgba(0, 0, 0, 0.3)",
        "FormsContentControlsOutlineBorderRadiusHover": 0,
        "FormsContentControlsOutlineBorderRadiusActive": 2,
        "FormsContentControlsMarkersBackground": "#FFFFFF",
        "FormsContentControlsMarkersBackgroundHover": "#E1E1E1",
        "FormsContentControlsMarkersBackgroundActive": "#CCCCCC",
        "FormsContentControlsOutlineMoverHover": "#444444",
        "FormsContentControlsOutlineMoverActive": "#444444",
        "BackgroundColorThumbnails": "#FFFFFF",
        "BackgroundColorThumbnailsActive": "#FFFFFF",
        "BackgroundColorThumbnailsHover": "#FFFFFF",
        "ThumbnailsPageOutline": "#C0C0C0",
        "ThumbnailsPageOutlineActive": "#306AD9",
        "ThumbnailsPageOutlineHover": "#85B1FF",
        "ThumbnailsPageNumberText": "#383838",
        "ThumbnailsPageNumberTextActive": "#383838",
        "ThumbnailsPageNumberTextHover": "#383838",
        "ThumbnailsLockColor": "#D34F4F",
        "BackgroundColorNotes": "#F3F3F3",
        "THEMES_THUMBNAIL_WIDTH": 88,
        "THEMES_THUMBNAIL_HEIGHT": 40,
        "THEMES_LAYOUT_THUMBNAIL_HEIGHT": 68,
        "BorderSplitterColor": "#CBCBCB",
        "SupportNotes": true,
        "SplitterWidthMM": 1,
        "ThumbnailScrollWidthNullIfNoScrolling": false,
        "AnimPaneBackground": "#f7f7f7",
        "AnimPaneItemFillSelected": "#cbcbcb",
        "AnimPaneItemFillHovered": "#e0e0e0",
        "AnimPaneButtonFill": "#e0e0e0",
        "AnimPaneButtonFillHovered": "#e0e0e0",
        "AnimPaneButtonFillDisabled": "#e0e0e0",
        "AnimPanePlayButtonFill": "#ffffff",
        "AnimPanePlayButtonOutline": "#c0c0c0",
        "AnimPaneEffectBarFillEntrance": "#77b583",
        "AnimPaneEffectBarOutlineEntrance": "#0e8a26",
        "AnimPaneEffectBarFillEmphasis": "#fbc37c",
        "AnimPaneEffectBarOutlineEmphasis": "#ff8e00",
        "AnimPaneEffectBarFillExit": "#f59a9a",
        "AnimPaneEffectBarOutlineExit": "#f23d3d",
        "AnimPaneEffectBarFillPath": "#a1cee3",
        "AnimPaneEffectBarOutlinePath": "#254662",
        "AnimPaneTimelineRulerOutline": "#cbcbcb",
        "AnimPaneTimelineRulerTick": "#cbcbcb",
        "AnimPaneTimelineScrollerFill": "#cbcbcb",
        "AnimPaneTimelineScrollerOutline": "#444444",
        "AnimPaneTimelineScrollerOpacity": 0,
        "AnimPaneTimelineScrollerOpacityHovered": 0.4,
        "AnimPaneTimelineScrollerOpacityActive": 1,
        "AnimPaneText": "#383838",
        "AnimPaneTextActive": "#383838",
        "AnimPaneTextHover": "#383838",
        "DemBackgroundColor": "#FFFFFF",
        "DemButtonBackgroundColor": "#FFFFFF",
        "DemButtonBackgroundColorHover": "#000000",
        "DemButtonBackgroundColorActive": "#000000",
        "DemButtonBorderColor": "#E1E1E1",
        "DemButtonTextColor": "#383838",
        "DemButtonTextColorActive": "#383838",
        "DemSplitterColor": "#E1E1E1",
        "DemTextColor": "#383838",
        "Background": "#F3F3F3",
        "BackgroundActive": "#E1E1E1",
        "BackgroundHighlighted": "#E1E1E1",
        "Border": "#E1E1E1",
        "BorderActive": "#B2B2B2",
        "BorderHighlighted": "#CBCBCB",
        "Color": "#404040",
        "ColorActive": "#404040",
        "ColorHighlighted": "#404040",
        "ColorFiltering": "#008636",
        "SheetViewCellBackground": "#00AB62",
        "SheetViewCellBackgroundPressed": "#5AEA98",
        "SheetViewCellBackgroundHover": "#38D080",
        "SheetViewCellTitleLabel": "#222222",
        "ColorDark": "#ffffff",
        "ColorDarkActive": "#ffffff",
        "ColorDarkHighlighted": "#c1c1c1",
        "ColorDarkFiltering": "#7AFFAF",
        "GroupDataBorder": "#222222",
        "EditorBorder": "#CBCBCB",
        "SelectAllIcon": "#949494",
        "SheetViewSelectAllIcon": "#00703E",
        "toolbar-header-document": "#F3F3F3",
        "toolbar-header-spreadsheet": "#F3F3F3",
        "toolbar-header-presentation": "#F3F3F3",
        "toolbar-header-pdf": "#F3F3F3",
        "toolbar-header-visio": "#F3F3F3",
        "text-toolbar-header-on-background-document": "#FFFFFF",
        "text-toolbar-header-on-background-spreadsheet": "#FFFFFF",
        "text-toolbar-header-on-background-presentation": "#FFFFFF",
        "text-toolbar-header-on-background-pdf": "#FFFFFF",
        "text-toolbar-header-on-background-visio": "#FFFFFF",
        "background-normal": "#FFFFFF",
        "background-toolbar": "#fff",
        "background-toolbar-tab": "#FFFFFF",
        "background-toolbar-additional": "#EFEFEF",
        "background-primary-dialog-button": "#306AD9",
        "background-notification-popover": "#FFF2C6",
        "background-notification-badge": "#FFD112",
        "background-scrim": "rgba(0, 0, 0, 0.2)",
        "background-loader": "rgba(0, 0, 0, 0.9)",
        "background-accent-button": "#306AD9",
        "background-contrast-popover": "#FFFFFF",
        "background-alt-key-hint": "#FFD112",
        "shadow-contrast-popover": "rgba(0, 0, 0, 0.3)",
        "background-fill-button": "#FFD112",
        "background-pane": "#F3F3F3",
        "background-pane-additional": "#F3F3F3",
        "highlight-button-hover": "rgba(0, 0, 0, 0.08)",
        "highlight-button-pressed": "rgba(0, 0, 0, 0.12)",
        "highlight-button-pressed-hover": "#B2B2B2",
        "highlight-primary-dialog-button-hover": "#1B55C1",
        "highlight-primary-dialog-button-pressed": "#003BA6",
        "highlight-header-button-hover": "rgba(0, 0, 0, 0.08)",
        "highlight-header-button-pressed": "rgba(0, 0, 0, 0.12)",
        "highlight-text-select": "#306AD9",
        "highlight-fill-button-hover": "#FFE388",
        "highlight-fill-button-pressed": "#D4AD00",
        "highlight-toolbar-tab-underline-document": "#446995",
        "highlight-toolbar-tab-underline-spreadsheet": "#3A8056",
        "highlight-toolbar-tab-underline-presentation": "#B75B44",
        "highlight-toolbar-tab-underline-pdf": "#AA5252",
        "highlight-toolbar-tab-underline-visio": "#444796",
        "highlight-header-tab-underline-document": "#446995",
        "highlight-header-tab-underline-spreadsheet": "#3A8056",
        "highlight-header-tab-underline-presentation": "#B75B44",
        "highlight-header-tab-underline-pdf": "#AA5252",
        "highlight-header-tab-underline-visio": "#444796",
        "highlight-comment-hover": "rgba(0, 0, 0, 0.08)",
        "highlight-comment-pressed": "rgba(0, 0, 0, 0.12)",
        "border-toolbar": "#CBCBCB",
        "border-toolbar-active-panel-top": "#F3F3F3",
        "border-toolbar-active-tab": "#FFFFFF",
        "border-divider": "#E1E1E1",
        "border-regular-control": "#E1E1E1",
        "border-preview-hover": "#85B1FF",
        "border-preview-select": "#306AD9",
        "border-control-focus": "#306AD9",
        "border-color-shading": "rgba(0, 0, 0, 0.2)",
        "border-contrast-popover": "#FFFFFF",
        "border-button-pressed-focus": "#1B55C1",
        "text-normal": "#383838",
        "text-normal-pressed": "#383838",
        "text-secondary": "#686868",
        "text-tertiary": "#7F7F7F",
        "text-link": "#306AD9",
        "text-link-hover": "#1B55C1",
        "text-link-active": "#1B55C1",
        "text-link-visited": "#306AD9",
        "text-inverse": "#FFFFFF",
        "text-toolbar-header": "#383838",
        "text-contrast-background": "#FFFFFF",
        "text-alt-key-hint": "#383838",
        "icon-normal": "#383838",
        "icon-normal-pressed": "#383838",
        "icon-toolbar-header": "#383838",
        "icon-success": "#00884D",
        "canvas-background": "#F3F3F3",
        "canvas-content-background": "#FFFFFF",
        "canvas-page-border": "#CBCBCB",
        "canvas-ruler-background": "#FFFFFF",
        "canvas-ruler-border": "#CBCBCB",
        "canvas-ruler-margins-background": "#E1E1E1",
        "canvas-ruler-mark": "#585858",
        "canvas-ruler-handle-border": "#585858",
        "canvas-ruler-handle-border-disabled": "#B2B2B2",
        "canvas-high-contrast": "#222222",
        "canvas-high-contrast-disabled": "#686868",
        "canvas-cell-title-background": "#F3F3F3",
        "canvas-cell-title-background-hover": "#E1E1E1",
        "canvas-cell-title-background-selected": "#E1E1E1",
        "canvas-cell-title-border": "#E1E1E1",
        "canvas-cell-title-border-hover": "#CBCBCB",
        "canvas-cell-title-border-selected": "#B2B2B2",
        "canvas-cell-title-text": "#404040",
        "canvas-dark-cell-title": "#686868",
        "canvas-dark-cell-title-hover": "#949494",
        "canvas-dark-cell-title-selected": "#383838",
        "canvas-dark-cell-title-border": "#404040",
        "canvas-dark-cell-title-border-hover": "#585858",
        "canvas-dark-cell-title-border-selected": "#222222",
        "canvas-scroll-thumb": "#F3F3F3",
        "canvas-scroll-thumb-hover": "rgba(0, 0, 0, 0.08)",
        "canvas-scroll-thumb-pressed": "rgba(0, 0, 0, 0.12)",
        "canvas-scroll-thumb-border": "#CBCBCB",
        "canvas-scroll-thumb-border-hover": "#B2B2B2",
        "canvas-scroll-thumb-border-pressed": "#949494",
        "canvas-scroll-arrow": "#949494",
        "canvas-scroll-arrow-hover": "#7F7F7F",
        "canvas-scroll-arrow-pressed": "#686868",
        "canvas-scroll-thumb-target": "#949494",
        "canvas-scroll-thumb-target-hover": "#7F7F7F",
        "canvas-scroll-thumb-target-pressed": "#686868",
        "canvas-sheet-view-cell-background": "#00AB62",
        "canvas-sheet-view-cell-background-hover": "#38D080",
        "canvas-sheet-view-cell-background-pressed": "#5AEA98",
        "canvas-sheet-view-cell-title-label": "#222222",
        "canvas-sheet-view-select-all-icon": "#00703E",
        "canvas-select-all-icon": "#949494",
        "canvas-anim-pane-background": "#f7f7f7",
        "canvas-anim-pane-item-fill-selected": "#cbcbcb",
        "canvas-anim-pane-item-fill-hovered": "#e0e0e0",
        "canvas-anim-pane-button-fill": "#e0e0e0",
        "canvas-anim-pane-button-fill-hovered": "#e0e0e0",
        "canvas-anim-pane-button-fill-disabled": "rgba(224, 224, 224, 0.4)",
        "canvas-anim-pane-play-button-fill": "#fff",
        "canvas-anim-pane-play-button-outline": "#c0c0c0",
        "canvas-anim-pane-effect-bar-entrance-fill": "#77b583",
        "canvas-anim-pane-effect-bar-entrance-outline": "#0e8a26",
        "canvas-anim-pane-effect-bar-emphasis-fill": "#fbc37c",
        "canvas-anim-pane-effect-bar-emphasis-outline": "#ff8e00",
        "canvas-anim-pane-effect-bar-exit-fill": "#f59a9a",
        "canvas-anim-pane-effect-bar-exit-outline": "#f23d3d",
        "canvas-anim-pane-effect-bar-path-fill": "#a1cee3",
        "canvas-anim-pane-effect-bar-path-outline": "#254662",
        "canvas-anim-pane-timeline-ruler-outline": "#cbcbcb",
        "canvas-anim-pane-timeline-ruler-tick": "#cbcbcb",
        "canvas-anim-pane-timeline-scroller-fill": "#cbcbcb",
        "canvas-anim-pane-timeline-scroller-outline": "#444",
        "canvas-anim-pane-timeline-scroller-opacity": "0",
        "canvas-anim-pane-timeline-scroller-opacity-hovered": "0.4",
        "canvas-anim-pane-timeline-scroller-opacity-active": "1",
        "toolbar-height-controls": "84px",
        "sprite-button-icons-uid": "mod25",
        "type": "light",
        "name": "theme-white"
    },
    "style": "body {color : #383838;background-color : #fff; }\n.defaultlable {color : #383838; }\n.aboutlable {color : #383838; }\na.aboutlink {color : #383838; }\n.form-control, .form-control[readonly], .form-control[disabled] {color : #383838;background-color : #FFFFFF;border-color : #E1E1E1; }\n.form-control:focus {border-color : #306AD9; }\n.form-control[disabled] { }\n.btn-text-default {background-color : #FFFFFF;border-color : #E1E1E1;color : #383838; }\n.btn-text-default:hover {background-color : rgba(0, 0, 0, 0.08); }\n.btn-text-default.active,\t\t.btn-text-default:active {background-color : rgba(0, 0, 0, 0.12) !important;color : #383838; }\n.btn-text-default[disabled]:hover,\t\t.btn-text-default.disabled:hover,\t\t.btn-text-default[disabled]:active,\t\t.btn-text-default[disabled].active,\t\t.btn-text-default.disabled:active,\t\t.btn-text-default.disabled.active {background-color : #FFFFFF !important;color : #383838; }\n.select2-container--default .select2-selection--single {color : #383838;background-color : #FFFFFF; }\n.select2-container--default .select2-selection--single .select2-selection__rendered {color : #383838; }\n.select2-results {background-color : #FFFFFF; }\n.select2-container--default .select2-results__option--highlighted[aria-selected] {background-color : rgba(0, 0, 0, 0.08) !important;color : #383838; }\n.select2-container--default .select2-results__option[aria-selected=true] {background-color : rgba(0, 0, 0, 0.12) !important;color : #383838; }\n.select2-dropdown, .select2-container--default .select2-selection--single {border-color : #E1E1E1 !important; }\n.select2-container--default.select2-container--open .select2-selection--single {border-color : #306AD9 !important; }\n.select2-container--default.select2-container--focus:not(.select2-container--open) .select2-selection--single {border-color : #E1E1E1 !important; }\n.select2-container--default.select2-container--open.select2-container--focus .select2-selection--single {border-color : #306AD9 !important; }\n.select2-search--dropdown {background-color : #FFFFFF !important; }\n.select2-container--default .select2-search--dropdown .select2-search__field {color : #383838;background-color : #FFFFFF;border-color : #E1E1E1; }\n.select2-container--default.select2-container--disabled .select2-selection--single {background-color : #FFFFFF; }\n.select2-container--default .select2-selection--single .select2-selection__arrow b {border-color : #383838 !important; }\n.select2-container--default.select2-container--open .select2-selection__arrow b {border-color : #383838 !important; }\n.ps .ps__rail-y:hover {background-color : #fff; }\n.ps .ps__rail-y.ps--clicking {background-color : #fff; }\n.ps__thumb-y {background-color : #FFFFFF;border-color : #E1E1E1 !important; }\n.ps__rail-y:hover > .ps__thumb-y {border-color : rgba(0, 0, 0, 0.08);background-color : rgba(0, 0, 0, 0.08) !important; }\n.ps .ps__rail-x:hover {background-color : #fff; }\n.ps .ps__rail-x.ps--clicking {background-color : #fff; }\n.ps__thumb-x {background-color : #FFFFFF;border-color : #E1E1E1 !important; }\n.ps__rail-x:hover > .ps__thumb-x {border-color : rgba(0, 0, 0, 0.08); }\na {color : #306AD9 !important; }\na:hover {color : #1B55C1 !important; }\na:active {color : #1B55C1 !important; }\na:visited {color : #306AD9 !important; }\n*::-webkit-scrollbar-track {background : #FFFFFF; }\n*::-webkit-scrollbar-track:hover {background : #EFEFEF; }\n*::-webkit-scrollbar-thumb {background-color : #fff;border-color : #E1E1E1; }\n*::-webkit-scrollbar-thumb:hover {background-color : rgba(0, 0, 0, 0.08); }\n.asc-plugin-loader {color : #383838; }\n"
};
