const LOCATOR_VALUES = [
    ["appendix", "Appendix"],
    ["article", "Article"],
    ["book", "Book"],
    ["chapter", "Chapter"],
    ["column", "Column"],
    ["figure", "Figure"],
    ["folio", "Folio"],
    ["issue", "Issue"],
    ["line", "Line"],
    ["note", "Note"],
    ["opus", "Opus"],
    ["page", "Page"],
    ["paragraph", "Paragraph"],
    ["part", "Part"],
    ["rule", "Rule"],
    ["section", "Section"],
    ["sub-verbo", "Sub verbo"],
    ["table", "Table"],
    ["title", "Title"],
    ["verses", "Verses"],
    ["volume", "Volume"],
];

export default LOCATOR_VALUES;
